// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestEmp2.Models;

namespace TestEmp2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestEmp2.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarPatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            AvatarPatch = "images/img_avatar1.png",
                            Department = 2,
                            Email = "hoangbachhiep2190@gmail.com",
                            Name = "hoangbachhiep"
                        },
                        new
                        {
                            EmployeeId = 2,
                            AvatarPatch = "images/img_avatar5.png",
                            Department = 0,
                            Email = "lequangvu11@gmail.com",
                            Name = "lequangvu23"
                        },
                        new
                        {
                            EmployeeId = 3,
                            AvatarPatch = "images/img_avatar5.png",
                            Department = 3,
                            Email = "lequangvu11@gmail.com",
                            Name = "lequangvu23"
                        },
                        new
                        {
                            EmployeeId = 4,
                            AvatarPatch = "images/img_avatar5.png",
                            Department = 1,
                            Email = "lequangvu11@gmail.com",
                            Name = "lequangvu23"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
